CREATE TABLE test(NAME VARCHAR(50), POINT INT);
INSERT INTO test VALUES("김태엽",100);
INSERT INTO test VALUES("김기태",100);

SELECT * FROM test;

CREATE TABLE notice(
	NO INT PRIMARY KEY auto_increment,
	title VARCHAR(200),
	content VARCHAR(1000),
	regdate DATETIME DEFAULT NOW(),
	visited INT DEFAULT 0
);

DESC notice;

INSERT INTO notice(title, content) values

COMMIT;

CREATE TABLE USER(
	id VARCHAR(30) PRIMARY KEY,
	pw VARCHAR(300) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	POINT INT DEFAULT 0,
	grade VARCHAR(4) DEFAULT "F",
	visted INT DEFAULT 1,
	tel VARCHAR(11),
	addr VARCHAR(150),
	email VARCHAR(100),
	birth DATE,
	regdate DATETIME DEFAULT NOW()
);

DROP TABLE USER;
DESC USER;

SELECT * FROM USER;
UPDATE user SET grade="A" WHERE id="admin";
COMMIT;


